const SONGS = [
  { title: "Better Together", artist: "Jack Johnson", key: "F", capo: 2, lyrics: `` },
  { title: "Brown Eyed Girl", artist: "Van Morrison", key: "G", capo: 0, lyrics: `` },
  { title: "Three Little Birds", artist: "Bob Marley", key: "A", capo: 0, lyrics: `` },
  { title: "Good People", artist: "Jack Johnson", key: "G", capo: 0, lyrics: `` },
  { title: "Encosta-te a Mim", artist: "", key: "", capo: 0, lyrics: `` },
  { title: "Country Roads", artist: "John Denver", key: "G", capo: 0, lyrics: `` },
  { title: "Bad Moon Rising", artist: "CCR", key: "D", capo: 0, lyrics: `` },
  { title: "Space Oddity", artist: "David Bowie", key: "C", capo: 0, lyrics: `` },
  { title: "Summer of '69", artist: "Bryan Adams", key: "D", capo: 0, lyrics: `` },
  { title: "Man on the Moon", artist: "R.E.M.", key: "C", capo: 0, lyrics: `` },
  { title: "While My Guitar Gently Weeps", artist: "The Beatles", key: "Am", capo: 0, lyrics: `` },
  { title: "74-75", artist: "The Connells", key: "G", capo: 0, lyrics: `` },
  { title: "Piano Man", artist: "Billy Joel", key: "C", capo: 0, lyrics: `` },
  { title: "Crazy Little Thing Called Love", artist: "Queen", key: "D", capo: 0, lyrics: `` },
  { title: "Angel", artist: "Massive Attack", key: "", capo: 0, lyrics: `` },
  { title: "Hotel California", artist: "Eagles", key: "Bm", capo: 0, lyrics: `` },
  { title: "I Got My Mind Set on You", artist: "George Harrison", key: "A", capo: 0, lyrics: `` },
  { title: "Billie Jean", artist: "Michael Jackson", key: "F#m", capo: 0, lyrics: `` },
  { title: "Born to Be Wild", artist: "Steppenwolf", key: "E", capo: 0, lyrics: `` },
  { title: "Boys Don't Cry", artist: "The Cure", key: "A", capo: 0, lyrics: `` },
  { title: "Call Me", artist: "Blondie", key: "Fm", capo: 0, lyrics: `` },
  { title: "Creep", artist: "Radiohead", key: "G", capo: 0, lyrics: `` },
  { title: "It's My Life", artist: "Bon Jovi", key: "Am", capo: 0, lyrics: `` },
  { title: "Dirty Old Town", artist: "The Pogues", key: "G", capo: 0, lyrics: `` },
  { title: "Blame It on Me", artist: "George Ezra", key: "C", capo: 0, lyrics: `` },
  { title: "Easy", artist: "Faith No More", key: "Ab", capo: 0, lyrics: `` },
  { title: "For What It's Worth", artist: "Buffalo Springfield", key: "E", capo: 0, lyrics: `` },
  { title: "Knocking on Heaven's Door", artist: "Bob Dylan", key: "G", capo: 0, lyrics: `` },
  { title: "Come Together", artist: "The Beatles", key: "Dm", capo: 0, lyrics: `` },
  { title: "Don't Look Back in Anger", artist: "Oasis", key: "C", capo: 0, lyrics: `` },
  { title: "La Bamba", artist: "Ritchie Valens", key: "C", capo: 0, lyrics: `` },
  { title: "One", artist: "U2", key: "Am", capo: 0, lyrics: `` },
  { title: "Friday I'm in Love", artist: "The Cure", key: "E", capo: 0, lyrics: `` },
  { title: "Folsom Prison Blues", artist: "Johnny Cash", key: "Bb", capo: 0, lyrics: `` },
  { title: "Fisherman's Blues", artist: "The Waterboys", key: "D", capo: 0, lyrics: `` },
  { title: "Misirlou", artist: "Dick Dale", key: "Em", capo: 0, lyrics: `` },
  { title: "Freedom (Pedro's Song)", artist: "", key: "", capo: 0, lyrics: `` },
  { title: "Heroes", artist: "David Bowie", key: "D", capo: 0, lyrics: `` },
  { title: "Don't You Forget About Me", artist: "Simple Minds", key: "Eb", capo: 0, lyrics: `` },
  { title: "How You Remind Me", artist: "Nickelback", key: "F", capo: 0, lyrics: `` },
  { title: "Gravity", artist: "John Mayer", key: "G", capo: 0, lyrics: `` },
  { title: "Hallelujah", artist: "Leonard Cohen", key: "C", capo: 0, lyrics: `` },
  { title: "Mother", artist: "Pink Floyd", key: "G", capo: 0, lyrics: `` },
  { title: "Mrs Robinson", artist: "Simon & Garfunkel", key: "E", capo: 0, lyrics: `` },
  { title: "Zombie", artist: "The Cranberries", key: "Em", capo: 0, lyrics: `` },
  { title: "Clandestino", artist: "Manu Chao", key: "Am", capo: 0, lyrics: `` },
  { title: "Octopus's Garden", artist: "The Beatles", key: "C", capo: 0, lyrics: `` },
  { title: "Paint It Black", artist: "The Rolling Stones", key: "Em", capo: 0, lyrics: `` },
  { title: "I Will Wait", artist: "Mumford & Sons", key: "D", capo: 0, lyrics: `` },
  { title: "Molly's Chambers", artist: "Kings of Leon", key: "E", capo: 0, lyrics: `` },
  { title: "Oye Como Va", artist: "Santana", key: "Am", capo: 0, lyrics: `` },
  { title: "Purple Rain", artist: "Prince", key: "Bb", capo: 0, lyrics: `` },
  { title: "Is This Love", artist: "Bob Marley", key: "G", capo: 0, lyrics: `` },
  { title: "Have You Ever Seen the Rain", artist: "CCR", key: "G", capo: 0, lyrics: `` },
  { title: "Personal Jesus", artist: "Depeche Mode", key: "E", capo: 0, lyrics: `` },
  { title: "Cocaine", artist: "Eric Clapton", key: "E", capo: 0, lyrics: `` },
  { title: "Riders on the Storm", artist: "The Doors", key: "Em", capo: 0, lyrics: `` },
  { title: "Ring of Fire", artist: "Johnny Cash", key: "G", capo: 0, lyrics: `` },
  { title: "Simple Man", artist: "Lynyrd Skynyrd", key: "C", capo: 0, lyrics: `` },
  { title: "Plush", artist: "Stone Temple Pilots", key: "G", capo: 0, lyrics: `` },
  { title: "Whiskey in the Jar", artist: "Thin Lizzy", key: "G", capo: 0, lyrics: `` },
  { title: "Save Tonight", artist: "Eagle Eye Cherry", key: "Am", capo: 0, lyrics: `` },
  { title: "Society", artist: "Eddie Vedder", key: "G", capo: 2, lyrics: `` },
  { title: "Should I Stay or Should I Go", artist: "The Clash", key: "D", capo: 0, lyrics: `` },
  { title: "Nothing Else Matters", artist: "Metallica", key: "Em", capo: 0, lyrics: `` },
  { title: "I Want to Break Free", artist: "Queen", key: "Bb", capo: 0, lyrics: `` },
  { title: "Rocket Man", artist: "Elton John", key: "G", capo: 0, lyrics: `` },
  { title: "Stand by Me", artist: "Ben E. King", key: "A", capo: 0, lyrics: `` },
  { title: "Johnny B. Goode", artist: "Chuck Berry", key: "Bb", capo: 0, lyrics: `` },
  { title: "Tainted Love", artist: "Soft Cell", key: "Am", capo: 0, lyrics: `` },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", key: "Am", capo: 0, lyrics: `` },
  { title: "Sultans of Swing", artist: "Dire Straits", key: "Dm", capo: 0, lyrics: `` },
  { title: "House of the Rising Sun", artist: "The Animals", key: "Am", capo: 0, lyrics: `` },
  { title: "Blowin' in the Wind", artist: "Bob Dylan", key: "G", capo: 0, lyrics: `` },
  { title: "Life on Mars", artist: "David Bowie", key: "F", capo: 0, lyrics: `` },
  { title: "Losing My Religion", artist: "R.E.M.", key: "Am", capo: 0, lyrics: `` },
  { title: "Suzie Q", artist: "CCR", key: "E", capo: 0, lyrics: `` },
  { title: "Money for Nothing", artist: "Dire Straits", key: "Gm", capo: 0, lyrics: `` },
  { title: "I Shot the Sheriff", artist: "Bob Marley", key: "Gm", capo: 0, lyrics: `` },
  { title: "The Wall", artist: "Pink Floyd", key: "Em", capo: 0, lyrics: `` },
  { title: "Rebel Yell", artist: "Billy Idol", key: "D", capo: 0, lyrics: `` },
  { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", key: "D", capo: 0, lyrics: `` },
  { title: "The End", artist: "The Doors", key: "Am", capo: 0, lyrics: `` },
  { title: "Ain't No Sunshine", artist: "Bill Withers", key: "Am", capo: 0, lyrics: `` },
  { title: "To Love Somebody", artist: "Bee Gees", key: "G", capo: 0, lyrics: `` },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", key: "E", capo: 0, lyrics: `` },
  { title: "Wagon Wheel", artist: "Old Crow Medicine Show", key: "G", capo: 0, lyrics: `` },
  { title: "Walk of Life", artist: "Dire Straits", key: "E", capo: 0, lyrics: `` },
  { title: "Sweet Caroline", artist: "Neil Diamond", key: "A", capo: 0, lyrics: `` },
  { title: "Kiss", artist: "Prince", key: "A", capo: 0, lyrics: `` },
  { title: "Why Worry", artist: "Dire Straits", key: "D", capo: 0, lyrics: `` },
  { title: "Winds of Change", artist: "Scorpions", key: "G", capo: 0, lyrics: `` },
  { title: "Wish You Were Here", artist: "Pink Floyd", key: "G", capo: 0, lyrics: `` },
  { title: "Love and Hate", artist: "Michael Kiwanuka", key: "Dm", capo: 0, lyrics: `` },
  { title: "Wild Rover", artist: "Traditional", key: "G", capo: 0, lyrics: `` },
  { title: "Proud Mary", artist: "CCR", key: "D", capo: 0, lyrics: `` },
  { title: "The Man Who Sold the World", artist: "David Bowie", key: "Dm", capo: 0, lyrics: `` },
  { title: "Wild Horses", artist: "The Rolling Stones", key: "G", capo: 2, lyrics: `` },
  { title: "Wonderwall", artist: "Oasis", key: "Em", capo: 2, lyrics: `` },
  { title: "Harvest Moon", artist: "Neil Young", key: "D", capo: 0, lyrics: `` },
  { title: "High and Dry", artist: "Radiohead", key: "A", capo: 0, lyrics: `` },
  { title: "The One I Love", artist: "R.E.M.", key: "Em", capo: 0, lyrics: `` },
  { title: "Stars", artist: "Simply Red", key: "E", capo: 0, lyrics: `` },
  { title: "Wicked Game", artist: "Chris Isaak", key: "Bm", capo: 0, lyrics: `` },
  { title: "Wonderful Tonight", artist: "Eric Clapton", key: "G", capo: 0, lyrics: `` },
  { title: "Comfortably Numb", artist: "Pink Floyd", key: "Bm", capo: 0, lyrics: `` },
  { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", key: "E", capo: 0, lyrics: `` },
  { title: "Closing Time", artist: "Semisonic", key: "G", capo: 0, lyrics: `` },
  { title: "Sex on Fire", artist: "Kings of Leon", key: "E", capo: 0, lyrics: `` },
  { title: "Escape (Piña Colada Song)", artist: "Rupert Holmes", key: "G", capo: 0, lyrics: `` },
  { title: "I Will Survive", artist: "Gloria Gaynor", key: "Am", capo: 0, lyrics: `` },
  { title: "Sunday Bloody Sunday", artist: "U2", key: "Bm", capo: 0, lyrics: `` },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", key: "Db", capo: 0, lyrics: `` },
  { title: "Nothing Compares 2 U", artist: "Sinéad O'Connor", key: "F", capo: 0, lyrics: `` },
  { title: "Sugar Man", artist: "Rodriguez", key: "Am", capo: 0, lyrics: `` },
  { title: "Secret Smile", artist: "Semisonic", key: "G", capo: 0, lyrics: `` },
  { title: "Something", artist: "The Beatles", key: "C", capo: 0, lyrics: `` },
  { title: "Who'll Stop the Rain", artist: "CCR", key: "G", capo: 0, lyrics: `` },
  { title: "Luka", artist: "Suzanne Vega", key: "A", capo: 0, lyrics: `` },
  { title: "Shout", artist: "Tears for Fears", key: "Dm", capo: 0, lyrics: `` },
  { title: "New Year's Day", artist: "U2", key: "D", capo: 0, lyrics: `` },
  { title: "Champagne Supernova", artist: "Oasis", key: "A", capo: 0, lyrics: `` },
  { title: "Imagine", artist: "John Lennon", key: "C", capo: 0, lyrics: `` },
  { title: "Hey Ho", artist: "The Lumineers", key: "C", capo: 3, lyrics: `` },
  { title: "Smooth", artist: "Santana ft. Rob Thomas", key: "Am", capo: 0, lyrics: `` },
];
